# This file defines the Windows Visual Studio PR build steps used during the CI loop
name: $(Date:yyyyMMdd).$(Rev:.r)

trigger: none # will disable CI builds entirely

pr:
  - master 

variables:
  vmImage: 'vs2017-win2016'

jobs:
  - job: UWPPR
    displayName: UWP PR
    strategy:
      matrix:
        X64Debug:
          BuildConfiguration: Debug
          BuildPlatform: x64
          UseRNFork: false
    pool:
      vmImage: $(vmImage)
    timeoutInMinutes: 45 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them
    steps:
      - checkout: self # self represents the repo where the initial Pipelines YAML file was found
      
      - script: echo $(UseRNFork)
      
      - template: templates/yarn-setup-install-build.yml
        parameters:
          useRNFork: $(UseRNFork)

  - job: Win32
    displayName: Win32
    pool:
      vmImage: $(vmImage)
    timeoutInMinutes: 45 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them
    steps:
      - checkout: self # self represents the repo where the initial Pipelines YAML file was found

      - template: templates/yarn-setup-install-build.yml
